import os
from openai import OpenAI


SYSTEM_PROMPT_RAG = """
You are a Medical Assistant generating a report for a Community Health Worker.
Your Goal is to Provide an optimal best-practice recommendation to solve the patient's complaint. The Community Health Worker can not help the patient beyond basic advice. You must provide disclaimers about the suggestions being generated by an AI model. Your output must not contain any markdowns. 
"""

def get_solution_from_context(client, patient_text):
    try:
        # 2. Generate Answer with LLM
        # We use the Context found by Chroma to ask GPT-4 for the specific answer
        response = client.chat.completions.create(
            model="gpt-4o",
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT_RAG},
                {"role": "user", "content": f"PATIENT COMPLAINT:\n{patient_text}"}
            ]
        )
        
        return response.choices[0].message.content

    except Exception as e:
        print(f"RAG Error: {e}")
        return "Error retrieving solution."